### ISSUE TITLE
使用demo的本地投屏功能崩溃

### ISSUE THREAD

**Issue by qq570026938** [devin1014/DLNA-Cast#10]

**Comment by devin1014** [comment]
贴个log给我

**Comment by qq570026938** [comment]
> 贴个log给我

最新的demo还没尝试，之前的demo可能存在问题

**Comment by qq570026938** [comment]
请问目前的框架可以正常使用了吗，想集成到项目里面，哈哈

**Comment by qq570026938** [comment]
本地投屏显示，投屏设备显示错误代码4，播放失败。搜索的设备有个什么千兆网，点击崩溃

**Comment by devin1014** [comment]
> 本地投屏显示，投屏设备显示错误代码4，播放失败。搜索的设备有个什么千兆网，点击崩溃

投本地视频是mp4格式的吗？播放器不能播放可能格式不对。千兆网崩溃，估计是类型不支持，我在做dms功能，所以你能搜到这个设备，原则上只需要搜索Renderer类型的设备就行。

**Comment by qq570026938** [comment]
现在还不能远程依赖吧？

**Comment by devin1014** [comment]
> 现在还不能远程依赖吧？

刚刚发布了第一个版本。
