### ISSUE TITLE
请问是否可以实现多台（如两台）手机同时投屏到一个屏幕上（如电视屏幕）？如何实现？

### ISSUE THREAD

**Issue by BruceLing** [devin1014/DLNA-Cast#14]

**Comment by wnpllrzodiac** [comment]
3play? dmr should DO the merge work or just run two seperate video?

**Comment by BruceLing** [comment]
run two seperate video on the same screen.   And the mobile phone can separately control the playback.

**Comment by wnpllrzodiac** [comment]
> 
> 
> run two seperate video on the same screen. And the mobile phone can separately control the playback.

like broadcast monitor wall?

**Comment by wnpllrzodiac** [comment]
I can try to write a app for you.

**Comment by devin1014** [comment]
如果这个是特定的需求是可以实现的。比如电视设备一下子注册两个设备，分贝收到通知后启动播放器，但是这个播放器需要定制（电视一分为二）。或者只注册一个设备，先投一个，然后其他设备再投的时候保留之前一个，再起一个播放器。
但是，这个需求有点奇怪，因为两个视频的话 声音会打架，我没有试过 能不能同时播放两个视频！曾经做过一个需求，平板上同时播放4个视频，但是只有特定的一个视频是有声音的，其他的静音。

**Comment by wnpllrzodiac** [comment]
> 
> 
> 如果这个是特定的需求是可以实现的。比如电视设备一下子注册两个设备，分贝收到通知后启动播放器，但是这个播放器需要定制（电视一分为二）。或者只注册一个设备，先投一个，然后其他设备再投的时候保留之前一个，再起一个播放器。
> 但是，这个需求有点奇怪，因为两个视频的话 声音会打架，我没有试过 能不能同时播放两个视频！曾经做过一个需求，平板上同时播放4个视频，但是只有特定的一个视频是有声音的，其他的静音。

播放多个音频是可以的。自动混音吧。但是没有意义啊。会变成混乱的鸡尾酒会的

**Comment by devin1014** [comment]
> > 如果这个是特定的需求是可以实现的。比如电视设备一下子注册两个设备，分贝收到通知后启动播放器，但是这个播放器需要定制（电视一分为二）。或者只注册一个设备，先投一个，然后其他设备再投的时候保留之前一个，再起一个播放器。
> > 但是，这个需求有点奇怪，因为两个视频的话 声音会打架，我没有试过 能不能同时播放两个视频！曾经做过一个需求，平板上同时播放4个视频，但是只有特定的一个视频是有声音的，其他的静音。
> 
> 播放多个音频是可以的。自动混音吧。但是没有意义啊。会变成混乱的鸡尾酒会的

确实没有意义，这个需求很奇怪。

**Comment by devin1014** [comment]
最近又过了下DLNA库，是可以投多个视频，在一个电视上的。
