### ISSUE TITLE
api问题

### ISSUE THREAD

**Issue by 2523955396** [devin1014/DLNA-Cast#15]
我导入了api 'devin1014.android:dlna-dmc:1.0.0'没法在声明中添加
在AndroidManifest.xml中需要添加如下

<service android:name="com.android.cast.dlna.dmc.DLNACastService"/>

**Comment by devin1014** [comment]
> 我导入了api 'devin1014.android:dlna-dmc:1.0.0'没法在声明中添加
> 在AndroidManifest.xml中需要添加如下

？？？添加什么？

**Comment by 2523955396** [comment]
这个依赖是有问题的

**Comment by 2523955396** [comment]
添加了没反应

**Comment by 2523955396** [comment]
![image](https://user-images.githubusercontent.com/44113373/117521130-c2c19880-afde-11eb-8bf3-5fe41295e5ff.png)
![image](https://user-images.githubusercontent.com/44113373/117521134-c9501000-afde-11eb-8c10-5d34a87b99ec.png)
![image](https://user-images.githubusercontent.com/44113373/117521152-e553b180-afde-11eb-9bd3-954bc0024432.png)
![image](https://user-images.githubusercontent.com/44113373/117521160-ea186580-afde-11eb-861c-e268ba80ebe2.png)

**Comment by 2523955396** [comment]
添加了依赖依然报错

**Comment by devin1014** [comment]
> 添加了依赖依然报错

Bintray 5月1号关闭后可能有点问题，导致库没有拉下来。之前测过，依赖没有问题。 有时间会上传到其他中心去。

**Comment by 2523955396** [comment]
划水行为非常恶劣，麻烦了

**Comment by devin1014** [comment]
> 划水行为非常恶劣，麻烦了

您是大佬，批评的是。

**Comment by 2523955396** [comment]
别别别，说着玩的

**Comment by devin1014** [comment]
更新了引用地址

**Comment by 2523955396** [comment]
好的------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月20日(星期四) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [devin1014/DLNA-Cast] api问题 (#15)
