### ISSUE TITLE
使用dmr投屏，腾讯视频播放出错

### ISSUE THREAD

**Issue by cxfksword** [devin1014/DLNA-Cast#17]
腾讯视频app投屏播放是成功的，但app上提示播放出错，有方法解决吗？
![](https://gitee.com/xetri/picgo/raw/master/img/20210623131404.png)
bilibili投屏没问题

**Comment by haoXu1990** [comment]
> 

楼主解决了吗，我也遇到了这个问题，我看 DMR 上面是 VideoViewRenderControl 的 getPosition 和 getDuration 是回复了数据的，但是在控制端收到的 position 获取不到总时长

**Comment by cxfksword** [comment]
> > 
> 
> 楼主解决了吗，我也遇到了这个问题，我看 DMR 上面是 VideoViewRenderControl 的 getPosition 和 getDuration 是回复了数据的，但是在控制端收到的 position 获取不到总时长

我没处理控制功能，只是腾讯视频app投屏后会请求获取播放状态，我返回当前播放状态就正常了

**Comment by haoXu1990** [comment]
> 



> > > 
> > 
> > 
> > 楼主解决了吗，我也遇到了这个问题，我看 DMR 上面是 VideoViewRenderControl 的 getPosition 和 getDuration 是回复了数据的，但是在控制端收到的 position 获取不到总时长
> 
> 我没处理控制功能，只是腾讯视频app投屏后会请求获取播放状态，我返回当前播放状态就正常了

感谢回复，已经解决了
