### ISSUE TITLE
renderer端图片貌似没有投屏成功

### ISSUE THREAD

**Issue by tangxuesong6** [devin1014/DLNA-Cast#20]
做DMR端的视频接收成功，图片没有成功过

**Comment by tangxuesong6** [comment]
fixed

**Comment by haoXu1990** [comment]
> fixed

请问你如何解决的，我目前查找到投屏的时候最后都是使用的 getAvService()来投屏的，如果音视频还好，图片的话这样感觉不科学，我看了下Cling 也没有找到 图片渲染相关的

**Comment by tangxuesong6** [comment]
> 

像这样
```
        sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/jpeg")));
        sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/png")));
        sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/gif")));
        sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/bmp")));
        sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/pjpeg")));
        sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/tiff")));
        sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/x-ms-bmp")));
```

**Comment by haoXu1990** [comment]
感谢您的回复
renderer端呢，总什么方法接收到的呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tangxuesong6 ***@***.***&gt;
发送时间: 2022年6月16日 20:34
收件人: devin1014/DLNA-Cast ***@***.***&gt;
抄送: haoXu1990 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[devin1014/DLNA-Cast] renderer端图片貌似没有投屏成功 (Issue #20)





   
像这样
         sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/jpeg")));         sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/png")));         sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/gif")));         sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/bmp")));         sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/pjpeg")));         sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/tiff")));         sinkProtocolInfo.add(new ProtocolInfo(MimeType.valueOf("image/x-ms-bmp")));
