### ISSUE TITLE
2个手机之间投屏失败

### ISSUE THREAD

**Issue by haoXu1990** [devin1014/DLNA-Cast#22]
Renderer 端目前只能正常播放和控制 M3u8: Iphone Sample 这一个
其它的MP4, M3u8:BT, M3u8:CC 和 图片， Rendere 都不能正常播放和现实。
请问如何需要如何解决呢，期待您的回复

**Comment by yongchao1210** [comment]
同样期待做的的更新！！！

**Comment by haoXu1990** [comment]
> 同样期待作者的更新！！！

可以加个好友，一起探讨

**Comment by yongchao1210** [comment]
> > 同样期待作者的更新！！！
> 
> 可以加个好友，一起探讨

留下联系方式！

**Comment by haoXu1990** [comment]
﻿这个不太清楚，可以在Renderer端AVtansportUri的参数里面看看，里面包含了很多媒体信息

286089659 可以加个q好友交流


发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yongchao1210 ***@***.***&gt;
发送时间: 2022年6月20日 16:38
收件人: devin1014/DLNA-Cast ***@***.***&gt;
抄送: haoXu1990 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[devin1014/DLNA-Cast] 2个手机之间投屏失败 (Issue #22)





 
我想在dmr 中获取 dmc投射设备的ip地址或者设备信息，有没有什么好的解决办法？

**Comment by devin1014** [comment]
> Renderer 端目前只能正常播放和控制 M3u8: Iphone Sample 这一个 其它的MP4, M3u8:BT, M3u8:CC 和 图片， Rendere 都不能正常播放和现实。 请问如何需要如何解决呢，期待您的回复

Renderer端只是最简单的一个VideoView demo，需要自己集成Player。VideoView能做的事情比较少。

**Comment by haoXu1990** [comment]
> 
感谢回复，这个问题解决了。
目前遇到了新的问题，能指点下吗
dmr 端上通过 notifyTransportStateChanged 上报的状态 dmc 无法收到

**Comment by cuileikun** [comment]
请问你是集成的什么播放器呢？

**Comment by devin1014** [comment]
已整体重构
