### ISSUE TITLE
爱奇艺等主流播放器DMC不适配

### ISSUE THREAD

**Issue by stephenLin914** [devin1014/DLNA-Cast#37]
使用bilibili，爱奇艺，腾讯视频等主流播放器，能够投屏到TV接收断，但是很快显示“播放结束”，无法控制音量，进度等。

**Comment by hsingming** [comment]
我也遇到了该问题，在IOS手机上使用主流播放器投屏到TV，视频APP提示“投屏失败”且无法控制音量进度。

**Comment by devin1014** [comment]
修复了部分问题，用爱奇艺做了测试，可以投屏，播放状态也可以同步，可以控制进度。但是无法控制音量，音量问题我再看下
