### ISSUE TITLE
請問閃退是什麼問題？

### ISSUE THREAD

**Issue by FongMi** [devin1014/DLNA-Cast#38]
![image](https://user-images.githubusercontent.com/3471963/230768289-c5bd9ef2-0401-4697-b173-910b14695c9e.png)

有添加以下依賴
implementation 'com.github.devin1014.DLNA-Cast:dlna-dmc:V1.0.0'

 maven { url 'https://jitpack.io' }
 maven {
    url 'http://4thline.org/m2'
    allowInsecureProtocol = true
}

**Comment by gjy12345** [comment]
YOUS

**Comment by FongMi** [comment]
遇到新問題
cannot be cast to java.lang.reflect.parameterizedtype

**Comment by FongMi** [comment]
都已解決

**Comment by liweiww123** [comment]
想问下如何解决的，demo跑不起来

**Comment by gjy12345** [comment]
YOUS

**Comment by liweiww123** [comment]
> 都已解決

想问下如何解决的呢
