### ISSUE TITLE
dmr接收到currentURIMetaData为空时报错

### ISSUE THREAD

**Issue by shan0404** [devin1014/DLNA-Cast#47]
currentURIMetaData包含了投屏过来的标题等信息，有的第三方投屏投屏过来只有currentURI，而currentURIMetaData为空时就会报错，
Error: Current state of service prevents invokingthat action. Parameter specified as non-null is null:method com.android.cast.dlna.dmr. service.AVTransportServicelmpl.setAVTransportURl, parametercurrentURlMetaData. (HT TP response was: 500

Internal Server Error)
大佬能修改为可空吗！

**Comment by devin1014** [comment]
好的，我改下。
