### ISSUE TITLE
请教一下DMR相关功能该怎么使用

### ISSUE THREAD

**Issue by gitcfly** [devin1014/DLNA-Cast#50]
请教一下该怎么使用DMR的功能呢，比如怎么实现播放器相关的接口？怎么把当前设备作为播放器端暴露到网络中，让别的设备可以搜索到，然后播放其他软件投送的视频？

**Comment by WeiLiuSH** [comment]
这个Demo中有实现的，自己看一下，有时间再更新下README文档

**Comment by devin1014** [comment]
Renderer Demo就是
